### ISSUE TITLE
Split up serializable models and content generation

### ISSUE THREAD

**Issue by YRafalsky** [Neschur/KB2#25]
At current moment content generation occurs inside serializable models (which user for save/load) - as result - any change in those classes makes old saves impossible to use.
Need 
1) split model and model data generation
2) (hard, but required) make old saves working (background migration on "load" event from current version to "v1" for example.
3) (optional, could be very hard) make game code flexible to models/entities change in future - in other words - if we decide to move from "v1" models to "v2" - we need to spend minimal time and commit minimal changes for this to reduce error possibility during this migration

**Comment by Neschur** [comment]
This is not good way, because it's very difficult to support. I started refactoring and migration to json format for saves
